name = kabosu_test7
scale = 1
filename = kabosu_v4vc.fbx
marketplaceID = {00000000-0000-0000-0000-000000000000}
texdir = textures
joint = jointRoot = Hips
joint = jointLean = Spine
joint = jointRightHand = RightHand
joint = jointNeck = Neck
joint = jointLeftHand = LeftHand
joint = jointEyeLeft = LeftEye
joint = jointHead = Head
joint = jointEyeRight = RightEye
bs = 
jointIndex = RightHandMiddle3 = 43
jointIndex = RightHandThumb1 = 21
jointIndex = LeftShoulder = 46
jointIndex = HeadTop_End_end = 82
jointIndex = LeftToe_End_end = 13
jointIndex = RightUpLeg = 2
jointIndex = LeftHandRing1 = 55
jointIndex = Head = 76
jointIndex = RightEye = 79
jointIndex = RightHandRing2 = 32
jointIndex = RightHandMiddle4 = 44
jointIndex = RightToeBase = 5
jointIndex = RightToe_End_end = 7
jointIndex = LeftHandRing4 = 58
jointIndex = LeftLeg = 9
jointIndex = RightHandRing4_end = 35
jointIndex = RightHandRing4 = 34
jointIndex = LeftFoot = 10
jointIndex = LeftHandRing3 = 57
jointIndex = LeftForeArm = 48
jointIndex = RightHandPinky2 = 37
jointIndex = LeftHandPinky4 = 53
jointIndex = LeftHandIndex3 = 62
jointIndex = LeftHandMiddle4 = 73
jointIndex = LeftHandPinky4_end = 54
jointIndex = LeftHandMiddle2 = 71
jointIndex = LeftHandIndex4_end = 64
jointIndex = LeftHandPinky3 = 52
jointIndex = LeftHandIndex4 = 63
jointIndex = RightToe_End = 6
jointIndex = kabosu = 83
jointIndex = RightFoot = 4
jointIndex = LeftHandIndex1 = 60
jointIndex = RightHandMiddle4_end = 45
jointIndex = LeftHandThumb4 = 68
jointIndex = Spine1 = 15
jointIndex = LeftHandThumb1 = 65
jointIndex = Spine = 14
jointIndex = Armature.001 = 0
jointIndex = RightHandRing3 = 33
jointIndex = Hips = 1
jointIndex = RightHandIndex1 = 26
jointIndex = RightHand = 20
jointIndex = HeadTop_End = 81
jointIndex = Spine2 = 16
jointIndex = RightHandThumb3 = 23
jointIndex = RightEye_end = 80
jointIndex = RightHandIndex3 = 28
jointIndex = RightHandPinky4_end = 40
jointIndex = RightHandThumb4_end = 25
jointIndex = LeftHandPinky1 = 50
jointIndex = LeftArm = 47
jointIndex = RightHandMiddle2 = 42
jointIndex = RightHandRing1 = 31
jointIndex = LeftEye_end = 78
jointIndex = RightHandPinky4 = 39
jointIndex = Neck = 75
jointIndex = RightHandMiddle1 = 41
jointIndex = LeftEye = 77
jointIndex = RightLeg = 3
jointIndex = RightHandThumb4 = 24
jointIndex = LeftHandMiddle1 = 70
jointIndex = RightHandIndex4 = 29
jointIndex = RightHandThumb2 = 22
jointIndex = RightHandIndex2 = 27
jointIndex = LeftToe_End = 12
jointIndex = LeftHandThumb4_end = 69
jointIndex = RightHandPinky1 = 36
jointIndex = LeftHandRing2 = 56
jointIndex = LeftHandIndex2 = 61
jointIndex = RightShoulder = 17
jointIndex = RightArm = 18
jointIndex = LeftToeBase = 11
jointIndex = LeftHandMiddle3 = 72
jointIndex = LeftUpLeg = 8
jointIndex = LeftHandPinky2 = 51
jointIndex = RightHandPinky3 = 38
jointIndex = LeftHandMiddle4_end = 74
jointIndex = LeftHandThumb2 = 66
jointIndex = RightHandIndex4_end = 30
jointIndex = LeftHandRing4_end = 59
jointIndex = LeftHand = 49
jointIndex = LeftHandThumb3 = 67
jointIndex = RightForeArm = 19
